author: Ch Pr
name: Build Rust Debian packages
description: Build Rust Debian packages with cargo deb in flexible environment.
inputs:
  apt-opts:
    description: Options to be passed to apt-get
    required: false
  before-build-hook:
    description: Shell command(s) to execute after installing build dependencies
      and before executing dpkg-buildpackage
    required: false
  docker-image:
    default: debian:stable-slim
    description: Name of a Docker image or path of a Dockerfile to use for the build container
    required: true
  extra-docker-args:
    description: Additional arguments to 'docker run' when starting the build container
    required: false
  extra-repo-keys:
    description: Extra ASCII-armored APT repository keys or paths to keyring files to trust in the build environment
    required: false
  extra-repos:
    description: Extra APT repositories to configure in the build environment (one-line-style or deb822-style format)
    required: false
  host-build-deps:
    description: Extra packages to be installed on host for build system
    required: false
  target-build-deps:
    description: Extra packages to be installed as build dependencies for build target
    required: false
  target-arch:
    default: amd64
    description: Target architecture for build (default is amd64)
    required: true
  setup-hook:
    description: Shell command(s) to execute after setting-up the build
      environment and before installing build dependencies
    required: false
  source-dir:
    default: ./
    description: Path relative to $GITHUB_WORKSPACE that contains the package sources
    required: true
  rust-features:
    description: optional features the rust package shall be built with
    required: false
  rust-version:
    default: 1.89.0
    description: optional rust version for build
    required: false 
  rust-buildtools:
    description: optional additional rust build tools to be installed from the crates.io. Cargo deb is installed by default. 
    required: false

outputs:
  artifact-dir:
    description: Build artifacts, including deb file and symbols
    value: ${{ steps.runner.outputs.output_path }}
      
runs:
  using: composite
  steps:
    - env:
        # Manually setting INPUT_* variables here until
        # https://github.com/actions/runner/issues/665 is resolved:
        INPUT_APT_OPTS: ${{ inputs.apt-opts }}
        INPUT_BEFORE_BUILD_HOOK: ${{ inputs.before-build-hook }}
        INPUT_DOCKER_IMAGE: ${{ inputs.docker-image }}
        INPUT_EXTRA_DOCKER_ARGS: ${{ inputs.extra-docker-args }}
        INPUT_EXTRA_REPO_KEYS: ${{  inputs.extra-repo-keys }}
        INPUT_EXTRA_REPOS: ${{  inputs.extra-repos }}
        INPUT_HOST_BUILD_DEPS: ${{ inputs.host-build-deps }}
        INPUT_TARGET_BUILD_DEPS: ${{ inputs.target-build-deps }}
        INPUT_TARGET_ARCH: ${{ inputs.target-arch }}
        INPUT_SETUP_HOOK: ${{ inputs.setup-hook }}
        INPUT_SOURCE_DIR: ${{ inputs.source-dir }}
        INPUT_RUST_FEATURES: ${{ inputs.rust-features }}
        INPUT_RUST_VERSION: ${{ inputs.rust-version }}
        INPUT_RUST_BUILDTOOLS: ${{ inputs.rust-buildtools }}
        # minimum Rust version aligns to minimum version, required to build cargo-deb
        # https://crates.io/crates/cargo-deb
        MIN_RUST_VERSION: 1.71.0
      id: runner
      run: ${{ github.action_path }}/scripts/run
      shell: bash
branding:
  color: red
  icon: package
