#!/bin/sh
set -eu

# load variables, created by install_build_deps
. ./build.env

PKG_CONFIG_LIBDIR="/usr/lib/$(dpkg-architecture -a "$INPUT_TARGET_ARCH" -qDEB_HOST_GNU_TYPE)"
export PKG_CONFIG_LIBDIR

if [ -n "$INPUT_RUST_FEATURES" ]; then
    INPUT_RUST_FEATURES="-- --features $(echo "$INPUT_RUST_FEATURES" | sed "s/[[:blank:]]*$//;s/ /,/g")"
    set -- -- --features "${INPUT_RUST_FEATURES}"
fi

cargo deb --separate-debug-symbols --target "${RUST_TARGET}" "{$@}"
