#!/bin/sh

set -eu

APT_CONF_FILE=/etc/apt/apt.conf.d/50build-deb-action
CARGO_DEB_VERSION="2.9.3"

# Checksums must be aligned with recent rust version and can be used from docker file from official rust docker image
# https://github.com/rust-lang/docker-rust/blob/1700955b94ae8a589562d872da74353028fffcf3/stable/bookworm/slim/Dockerfile
get_rust_arch() {
    dpkgArch="${1}"
    case "${dpkgArch##*-}" in
        amd64) rustArch='x86_64-unknown-linux-gnu'; rustupSha256='20a06e644b0d9bd2fbdbfd52d42540bdde820ea7df86e92e533c073da0cdd43c' ;;
        armhf) rustArch='armv7-unknown-linux-gnueabihf'; rustupSha256='3b8daab6cc3135f2cd4b12919559e6adaee73a2fbefb830fadf0405c20231d61' ;;
        arm64) rustArch='aarch64-unknown-linux-gnu'; rustupSha256='e3853c5a252fca15252d07cb23a1bdd9377a8c6f3efa01531109281ae47f841c' ;;
        i386) rustArch='i686-unknown-linux-gnu'; rustupSha256='a5db2c4b29d23e9b318b955dd0337d6b52e93933608469085c924e0d05b1df1f' ;;
        ppc64el) rustArch='powerpc64le-unknown-linux-gnu'; rustupSha256='acd89c42b47c93bd4266163a7b05d3f26287d5148413c0d47b2e8a7aa67c9dc0' ;;
        s390x) rustArch='s390x-unknown-linux-gnu'; rustupSha256='726b7fd5d8805e73eab4a024a2889f8859d5a44e36041abac0a2436a52d42572' ;;
        *) echo >&2 "unsupported architecture: ${dpkgArch}"; exit 1 ;;
    esac
}

export DEBIAN_FRONTEND=noninteractive

cat >"$APT_CONF_FILE" <<-EOF
	APT::Get::Assume-Yes "yes";
	APT::Install-Recommends "no";
	Acquire::Languages "none";
	quiet "yes";
EOF

cat /etc/os-release

# install build architecture
dpkg --add-architecture "$INPUT_TARGET_ARCH"
if [ -n "$INPUT_TARGET_BUILD_DEPS" ]; then
    INPUT_TARGET_BUILD_DEPS=$(echo "$INPUT_TARGET_BUILD_DEPS" | sed "s/[[:blank:]]*$/ /;s/ /:$INPUT_TARGET_ARCH /g")
fi
BUILD_DEPS="$INPUT_HOST_BUILD_DEPS $INPUT_TARGET_BUILD_DEPS crossbuild-essential-$INPUT_TARGET_ARCH libc-dev:$INPUT_TARGET_ARCH"
printf 'APT::Get::Host-Architecture "%s";\n' "$INPUT_TARGET_ARCH" >>"$APT_CONF_FILE"
get_rust_arch "${INPUT_TARGET_ARCH}"
RUST_TARGET="${rustArch}"

# add rust target to build envs
echo "RUST_TARGET='${RUST_TARGET}'" >> build.env

# debconf has priority “required” and is indirectly depended on by some
# essential packages. It is reasonably safe to blindly assume it is installed.
printf "man-db man-db/auto-update boolean false\n" | debconf-set-selections

if printf "%s\n" "$INPUT_EXTRA_REPOS" | grep -q '^deb'; then
	extra_repos_ext=.list
else
	extra_repos_ext=.sources
fi
printf "%s\n" "$INPUT_EXTRA_REPOS" >"/etc/apt/sources.list.d/build-deb-action${extra_repos_ext}"

apt-get update

# shellcheck disable=SC2086
apt-get install $INPUT_APT_OPTS -- wget ca-certificates pkg-config build-essential $BUILD_DEPS

# install rust
# inspired by official rust docker image 
# https://github.com/rust-lang/docker-rust/blob/1700955b94ae8a589562d872da74353028fffcf3/stable/bookworm/slim/Dockerfile

# create rust config
mkdir "$INPUT_SOURCE_DIR/.cargo"
cat <<- EOT >> "$INPUT_SOURCE_DIR/.cargo/config.toml"
[target.${rustArch}]
linker = "$(dpkg-architecture -a "$INPUT_TARGET_ARCH" -qDEB_HOST_GNU_TYPE)-gcc"
EOT

# get rust arch for build system architecture
get_rust_arch "$(dpkg --print-architecture)"

# download and prepare rustup-init
url="https://static.rust-lang.org/rustup/archive/1.28.2/${rustArch}/rustup-init"
wget "$url"
echo "${rustupSha256} *rustup-init" | sha256sum -c -
chmod +x rustup-init

# install Rust via rustup-init
# rustup-init throws nonblocking errors when installed in a docker containers as root. The error is caused as $HOME directory is not /root but /home/runner.

if [ -n "$INPUT_RUST_VERSION" ]; then
    set -- --default-toolchain "${INPUT_RUST_VERSION}"
fi

./rustup-init -y --no-modify-path --profile minimal "$@" --default-host "${rustArch}" --target "$RUST_TARGET"
rm rustup-init

# install required rust build tools
# shellcheck disable=SC2086
cargo install --force --locked cargo-deb@$CARGO_DEB_VERSION $INPUT_RUST_BUILDTOOLS
